//! Build-time metadata (version, git commit, build date) generated by `shadow-rs`, used for
//! `joshuto --version`.

#![allow(clippy::needless_raw_string_hashes)]
use shadow_rs::shadow;
shadow!(build);

pub use self::build::*;
