name: "Nix Flakes"

on:
  push:
    branches: [dev, main]

  pull_request:
    branches: [dev, main]

jobs:
  build-nix-flake:
    name: Build Nix Flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Build Nix Flake
        run: nix build

      - name: Test executable
        run: ./result/bin/joshuto version
